Repository UBC-MDS/RMLViz, pull requests merged in 2020-03, with the labels that each got.

#17 Updated Contributing
  CONTRIBUTING.md
Labels: documentation

#26 Model comparison table function and tests setup.
  DESCRIPTION
  NAMESPACE
  R/model_comparison_table.R
  R/modelcomptab.R
  man/confusion_matrix.Rd
  man/model_comparison_table.Rd
  man/modelcomptab.Rd
  tests/testthat/test-model_comparison_table.R
  tests/testthat/test-modelcomptab.R
Labels: function-dev

#27 Created Confusion matrix function as well as unit test functions
  DESCRIPTION
  NAMESPACE
  R/confusion_matrix.R
  man/confusion_matrix.Rd
  man/model_comparison_table.Rd
  man/plot_train_valid_error.Rd
  tests/testthat/test-confusion_matrix.R
Labels: function-dev

#34 Fixed warning regarding confusion matrix function
  R/confusion_matrix.R
Labels: function-dev

#40 fix: closes issue #39
  NAMESPACE
  R/model_comparison_table.R
  man/model_comparison_table.Rd
  man/plot_train_valid_error.Rd
  tests/testthat/test-model_comparison_table.R
Labels: enhancement

#44 Removed warning lines
  README.md
Labels: documentation
