Repository UBC-MDS/RMLViz, pull requests merged in 2020-02, with the labels that each got.

#5 Built the model comparison function.
  DESCRIPTION
  NAMESPACE
  R/modelcomptab.R
  man/modelcomptab.Rd
  tests/testthat/test-modelcomptab.R
Labels: function-dev

#7 README Updated and Confusion matrix function skeleton created
  R/confusion_matrix.R
  README.Rmd
  README.html
  README.md
  tests/testthat/test-confusion_matrix.R
Labels: documentation, function-dev

#13 Contributing file
  CONTRIBUTING.md
Labels: documentation
